// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GetFitterGetBigger.API.IntegrationTests.Features.Exercise
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ExerciseCoachNotesSynchronizationFeature : object, Xunit.IClassFixture<ExerciseCoachNotesSynchronizationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ExerciseCoachNotesSynchronizationFeature(ExerciseCoachNotesSynchronizationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Exercise", "Exercise Coach Notes Synchronization", "  As a fitness application\n  I want to manage coach notes with proper ordering\n  " +
                    "So that users receive instructions in the correct sequence", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("I am authenticated as a user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            await testRunner.AndAsync("the database has reference data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            await testRunner.WhenAsync("I send a GET request to \"/api/ReferenceTables/MuscleGroups\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
            await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            await testRunner.AndAsync("I store the first item from the response as \"firstMuscleGroup\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            await testRunner.WhenAsync("I send a GET request to \"/api/ReferenceTables/MuscleRoles\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
            await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            await testRunner.AndAsync("I store the first item from the response as \"firstMuscleRole\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create exercise with ordered coach notes returns notes in correct order")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Coach Notes Synchronization")]
        [Xunit.TraitAttribute("Description", "Create exercise with ordered coach notes returns notes in correct order")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "coach-notes")]
        public async System.Threading.Tasks.Task CreateExerciseWithOrderedCoachNotesReturnsNotesInCorrectOrder()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "coach-notes"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create exercise with ordered coach notes returns notes in correct order", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""Coach Notes Order Test"",
  ""description"": ""Testing coach notes ordering"",
  ""coachNotes"": [
    {
      ""text"": ""Step 3"",
      ""order"": 3
    },
    {
      ""text"": ""Step 1"",
      ""order"": 1
    },
    {
      ""text"": ""Step 2"",
      ""order"": 2
    }
  ],
  ""exerciseTypeIds"": [""exercisetype-22334455-6677-8899-aabb-ccddeeff0011""],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": ""kineticchaintype-f5d5a2de-9c4e-4b87-b8c3-5d1e17d0b1f4"",
  ""exerciseWeightTypeId"": ""exerciseweighttype-b2e4d3c5-6a7b-5c8d-9e0f-1a2b3c4d5e6f"",
  ""muscleGroups"": [
    {
      ""muscleGroupId"": ""<firstMuscleGroup.id>"",
      ""muscleRoleId"": ""<firstMuscleRole.id>""
    }
  ],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should have property \"coachNotes\" as array with length 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[0].text\" should be \"Step 1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[0].order\" should be \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[1].text\" should be \"Step 2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[1].order\" should be \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[2].text\" should be \"Step 3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[2].order\" should be \"3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create exercise with duplicate coach note orders handles gracefully")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Coach Notes Synchronization")]
        [Xunit.TraitAttribute("Description", "Create exercise with duplicate coach note orders handles gracefully")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "coach-notes")]
        public async System.Threading.Tasks.Task CreateExerciseWithDuplicateCoachNoteOrdersHandlesGracefully()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "coach-notes"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create exercise with duplicate coach note orders handles gracefully", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""Duplicate Order Test"",
  ""description"": ""Testing duplicate coach note orders"",
  ""coachNotes"": [
    {
      ""text"": ""First with order 1"",
      ""order"": 1
    },
    {
      ""text"": ""Second with order 1"",
      ""order"": 1
    },
    {
      ""text"": ""Third with order 2"",
      ""order"": 2
    }
  ],
  ""exerciseTypeIds"": [""exercisetype-22334455-6677-8899-aabb-ccddeeff0011""],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": ""kineticchaintype-f5d5a2de-9c4e-4b87-b8c3-5d1e17d0b1f4"",
  ""exerciseWeightTypeId"": ""exerciseweighttype-b2e4d3c5-6a7b-5c8d-9e0f-1a2b3c4d5e6f"",
  ""muscleGroups"": [
    {
      ""muscleGroupId"": ""<firstMuscleGroup.id>"",
      ""muscleRoleId"": ""<firstMuscleRole.id>""
    }
  ],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should have property \"coachNotes\" as array with length 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create exercise returns coach notes in order")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Coach Notes Synchronization")]
        [Xunit.TraitAttribute("Description", "Create exercise returns coach notes in order")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "coach-notes")]
        public async System.Threading.Tasks.Task CreateExerciseReturnsCoachNotesInOrder()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "coach-notes"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create exercise returns coach notes in order", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""Create Test with Unordered Notes"",
  ""description"": ""Testing that created exercise returns notes in order"",
  ""coachNotes"": [
    {
      ""text"": ""Last step"",
      ""order"": 99
    },
    {
      ""text"": ""First step"",
      ""order"": 1
    },
    {
      ""text"": ""Middle step"",
      ""order"": 50
    }
  ],
  ""exerciseTypeIds"": [""exercisetype-22334455-6677-8899-aabb-ccddeeff0011""],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": ""kineticchaintype-f5d5a2de-9c4e-4b87-b8c3-5d1e17d0b1f4"",
  ""exerciseWeightTypeId"": ""exerciseweighttype-b2e4d3c5-6a7b-5c8d-9e0f-1a2b3c4d5e6f"",
  ""muscleGroups"": [
    {
      ""muscleGroupId"": ""<firstMuscleGroup.id>"",
      ""muscleRoleId"": ""<firstMuscleRole.id>""
    }
  ],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should have property \"coachNotes\" as array with length 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[0].text\" should be \"First step\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[0].order\" should be \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[1].text\" should be \"Middle step\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[1].order\" should be \"50\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[2].text\" should be \"Last step\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"coachNotes[2].order\" should be \"99\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get exercises list returns exercises with coach notes")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Coach Notes Synchronization")]
        [Xunit.TraitAttribute("Description", "Get exercises list returns exercises with coach notes")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "coach-notes")]
        public async System.Threading.Tasks.Task GetExercisesListReturnsExercisesWithCoachNotes()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "coach-notes"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get exercises list returns exercises with coach notes", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""List Test Exercise 1"",
  ""description"": ""First exercise for list test"",
  ""coachNotes"": [
    {
      ""text"": ""Exercise 1 Note 1"",
      ""order"": 1
    },
    {
      ""text"": ""Exercise 1 Note 2"",
      ""order"": 2
    }
  ],
  ""exerciseTypeIds"": [""exercisetype-22334455-6677-8899-aabb-ccddeeff0011""],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": ""kineticchaintype-f5d5a2de-9c4e-4b87-b8c3-5d1e17d0b1f4"",
  ""exerciseWeightTypeId"": ""exerciseweighttype-b2e4d3c5-6a7b-5c8d-9e0f-1a2b3c4d5e6f"",
  ""muscleGroups"": [
    {
      ""muscleGroupId"": ""<firstMuscleGroup.id>"",
      ""muscleRoleId"": ""<firstMuscleRole.id>""
    }
  ],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""List Test Exercise 2"",
  ""description"": ""Second exercise for list test"",
  ""coachNotes"": [
    {
      ""text"": ""Exercise 2 Note 1"",
      ""order"": 1
    }
  ],
  ""exerciseTypeIds"": [""exercisetype-22334455-6677-8899-aabb-ccddeeff0011""],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": ""kineticchaintype-f5d5a2de-9c4e-4b87-b8c3-5d1e17d0b1f4"",
  ""exerciseWeightTypeId"": ""exerciseweighttype-b2e4d3c5-6a7b-5c8d-9e0f-1a2b3c4d5e6f"",
  ""muscleGroups"": [
    {
      ""muscleGroupId"": ""<firstMuscleGroup.id>"",
      ""muscleRoleId"": ""<firstMuscleRole.id>""
    }
  ],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                await testRunner.WhenAsync("I send a GET request to \"/api/exercises?pageSize=50\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should have property \"items\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ExerciseCoachNotesSynchronizationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ExerciseCoachNotesSynchronizationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
