// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GetFitterGetBigger.API.IntegrationTests.Features.Exercise
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ExerciseRestTypeExclusivityFeature : object, Xunit.IClassFixture<ExerciseRestTypeExclusivityFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ExerciseRestTypeExclusivityFeature(ExerciseRestTypeExclusivityFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Exercise", "Exercise Rest Type Exclusivity", "  As a fitness application\n  I want to ensure that REST type exercises cannot be " +
                    "combined with other types\n  So that exercise categorization remains consistent", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("the database has reference data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            await testRunner.GivenAsync("I am authenticated as a user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create exercise with only REST type succeeds")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Rest Type Exclusivity")]
        [Xunit.TraitAttribute("Description", "Create exercise with only REST type succeeds")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "rest-exclusivity")]
        public async System.Threading.Tasks.Task CreateExerciseWithOnlyRESTTypeSucceeds()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "rest-exclusivity"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create exercise with only REST type succeeds", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""Valid Rest Period"",
  ""description"": ""A rest period between exercises"",
  ""coachNotes"": [
    {
      ""text"": ""Take a 90 second break"",
      ""order"": 1
    },
    {
      ""text"": ""Hydrate during this time"",
      ""order"": 2
    }
  ],
  ""exerciseTypeIds"": [""exercisetype-d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f9a""],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": null,
  ""exerciseWeightTypeId"": null,
  ""muscleGroups"": [],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should have property \"name\" with value \"Valid Rest Period\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response should have property \"exerciseTypes\" as array with length 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response property \"exerciseTypes[0].value\" should be \"Rest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create exercise with REST and Warmup types returns bad request")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Rest Type Exclusivity")]
        [Xunit.TraitAttribute("Description", "Create exercise with REST and Warmup types returns bad request")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "rest-exclusivity")]
        public async System.Threading.Tasks.Task CreateExerciseWithRESTAndWarmupTypesReturnsBadRequest()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "rest-exclusivity"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create exercise with REST and Warmup types returns bad request", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""Invalid Rest with Warmup"",
  ""description"": ""Trying to combine Rest with Warmup"",
  ""coachNotes"": [],
  ""exerciseTypeIds"": [
    ""exercisetype-d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f9a"",
    ""exercisetype-a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d""
  ],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": null,
  ""exerciseWeightTypeId"": null,
  ""muscleGroups"": [],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create exercise with REST and Workout types returns bad request")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Rest Type Exclusivity")]
        [Xunit.TraitAttribute("Description", "Create exercise with REST and Workout types returns bad request")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "rest-exclusivity")]
        public async System.Threading.Tasks.Task CreateExerciseWithRESTAndWorkoutTypesReturnsBadRequest()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "rest-exclusivity"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create exercise with REST and Workout types returns bad request", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""Invalid Rest with Workout"",
  ""description"": ""Trying to combine Rest with Workout"",
  ""coachNotes"": [],
  ""exerciseTypeIds"": [
    ""exercisetype-b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e"",
    ""exercisetype-d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f9a""
  ],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": null,
  ""exerciseWeightTypeId"": null,
  ""muscleGroups"": [],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create exercise with REST and all other types returns bad request")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Rest Type Exclusivity")]
        [Xunit.TraitAttribute("Description", "Create exercise with REST and all other types returns bad request")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "rest-exclusivity")]
        public async System.Threading.Tasks.Task CreateExerciseWithRESTAndAllOtherTypesReturnsBadRequest()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "rest-exclusivity"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create exercise with REST and all other types returns bad request", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""Invalid Rest with All Types"",
  ""description"": ""Trying to combine Rest with all other types"",
  ""coachNotes"": [],
  ""exerciseTypeIds"": [
    ""exercisetype-a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d"",
    ""exercisetype-b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e"",
    ""exercisetype-c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f"",
    ""exercisetype-d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f9a""
  ],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": null,
  ""exerciseWeightTypeId"": null,
  ""muscleGroups"": [],
  ""equipmentIds"": [],
  ""bodyPartIds"": [],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create exercise without REST type allows multiple types")]
        [Xunit.TraitAttribute("FeatureTitle", "Exercise Rest Type Exclusivity")]
        [Xunit.TraitAttribute("Description", "Create exercise without REST type allows multiple types")]
        [Xunit.TraitAttribute("Category", "exercise")]
        [Xunit.TraitAttribute("Category", "rest-exclusivity")]
        public async System.Threading.Tasks.Task CreateExerciseWithoutRESTTypeAllowsMultipleTypes()
        {
            string[] tagsOfScenario = new string[] {
                    "exercise",
                    "rest-exclusivity"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create exercise without REST type allows multiple types", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a POST request to \"/api/exercises\" with body:", @"{
  ""name"": ""Multiple Types Without Rest"",
  ""description"": ""Exercise with multiple non-Rest types"",
  ""coachNotes"": [],
  ""exerciseTypeIds"": [
    ""exercisetype-a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d"",
    ""exercisetype-b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e"",
    ""exercisetype-c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f""
  ],
  ""isUnilateral"": false,
  ""difficultyId"": ""difficultylevel-8a8adb1d-24d2-4979-a5a6-0d760e6da24b"",
  ""kineticChainId"": ""kineticchaintype-f5d5a2de-9c4e-4b87-b8c3-5d1e17d0b1f4"",
  ""exerciseWeightTypeId"": ""exerciseweighttype-b2e4d3c5-6a7b-5c8d-9e0f-1a2b3c4d5e6f"",
  ""muscleGroups"": [
    {
      ""muscleGroupId"": ""musclegroup-ccddeeff-0011-2233-4455-667788990011"",
      ""muscleRoleId"": ""musclerole-5d8e9a7b-3c2d-4f6a-9b8c-1e5d7f3a2c9b""
    }
  ],
  ""equipmentIds"": [],
  ""bodyPartIds"": [""bodypart-7c5a2d6e-e87e-4c8a-9f1d-9eb734f3df3c""],
  ""movementPatternIds"": []
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should have property \"name\" with value \"Multiple Types Without Rest\"" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                await testRunner.AndAsync("the response should have property \"exerciseTypes\" as array with length 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ExerciseRestTypeExclusivityFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ExerciseRestTypeExclusivityFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
